package Funcionalidades;

public enum NomeTela {
	TELAORCAMENTOS,
	TELAEDITARORCAMENTO,
	TELAFILTRARORCAMENTOS,
	TELACADASTROORCAMENTO,
	TELAFORNECEDORES,
	TELAFORNECEDORESFINANCAS,
	TELAADDFORNECEDORORCAMENTO,
	TELAADDFORNECEDORPACOTE,
	TELAFILTRARFORNECEDOR,
	TELACADASTROFORNECEDOR,
	TELADETALHARFORNECEDOR,
	TELAREUNIOES,
	TELASERVICOS,
	TELAADDSERVICOFORNECEDOR,
	TELAPACOTES,
	TELACADASTROPACOTE,
	TELACADASTROCLIENTE,
	TELAPLANILHAFINANCAS,
	TELALOGINADMIN,
	TELAPRINCIPAL;
}