package Interface;

public enum NomeTela {
	TELA_ORCAMENTOS,
	TELA_EDITAR_ORCAMENTO,
	TELA_FILTRAR_ORCAMENTOS,
	TELA_CADASTRO_ORCAMENTO,
	TELA_FORNECEDORES,
	TELA_FORNECEDORES_FINANCAS,
	TELA_ADD_FORNECEDOR_CAD_ORCAMENTO,
	TELA_ADD_FORNECEDOR_EDT_ORCAMENTO,
	TELA_ADD_FORNECEDOR_PACOTE,
	TELA_FILTRAR_FORNECEDOR,
	TELA_CADASTRO_FORNECEDOR,
	TELA_DETALHAR_FORNECEDOR,
	TELA_REUNIOES,
	TELA_SERVICOS,
	TELA_ADD_SERVICO_FORNECEDOR,
	TELA_PACOTES,
	TELA_CADASTRO_PACOTE,
	TELA_CADASTRO_CLIENTE,
	TELA_PLANILHA_FINANCAS,
	TELA_LOGIN_ADMIN,
	TELA_PRINCIPAL,
	TELA_LISTAR_REUNIOES;
}