package ElementosGraficos;

public enum NomeTela {
	TELA_ORCAMENTOS,
	TELA_EDITAR_ORCAMENTO,
	TELA_CADASTRO_ORCAMENTO,
	TELA_FORNECEDORES,
	TELA_FILTRAR_FORNECEDOR,
	TELA_CADASTRO_FORNECEDOR,
	TELA_DETALHAR_FORNECEDOR,
	TELA_REUNIOES,
	TELA_SERVICOS,
	TELA_PACOTES,
	TELA_CADASTRO_PACOTE,
	TELA_CADASTRO_CLIENTE,
	TELA_PLANILHA_FINANCAS,
	TELA_LOGIN_ADMIN,
	TELA_PRINCIPAL,
}